xyz

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -124,11 +124,12 @@ jobs:
           TOX_SHOW_OUTPUT: "True"
           TOXENV: ${{ matrix.tox-env }}
         run: |
-          poetry lock
-          export DEPENDENCY_REGEX="$(poetry show -T --without=dev | awk '{print $1}' | paste -s -d '|' -)"
+          DEPENDENCY_REGEX="$(poetry show -T --without=dev | awk '{print $1}' | paste -s -d '|' -)"
+          [[ -z "$DEPENDENCY_REGEX" ]] && { echo "can't source dependencies" } ; exit 1
           echo ::deps $DEPENDENCY_REGEX
           sed -i -E 's/('"$DEPENDENCY_REGEX"')( = )"(\^|>=)([0-9])/\1\2"==\4/' pyproject.toml
-          # git diff
+          poetry lock
+          git diff
           # tox run-parallel -p 2
 
   # report-coverage:
